language: php

php:
  - 7.0

matrix:
  fast_finish: true

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  - composer global require drush/drush:8.*

  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

before_script:
  - cd ..
  - mysql -e 'create database drupal'
  - drush --yes core-quick-drupal tmp --no-server --db-url=mysql://root:@127.0.0.1/drupal --profile=standard
  - mv tmp/drupal .
  - ls -al drupal
  - mv asu_brand drupal/modules/
  - cd drupal
  - drush status

script: drush en asu_brand -y
