language: php

php:
  - 7.0

matrix:
  fast_finish: true

mysql:
  database: mmenavas_asu_brand_test
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php7.0 php7.0-mysql

  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # install drush globally
  - composer global require drush/drush:6.*

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database mmenavas_asu_brand_test'
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/mmenavas_asu_brand_test --enable=simpletest mmenavas_asu_brand_test

  # reference and enable travis_ci_drupal_module_example in build site
  - ln -s $(readlink -e $(cd -)) mmenavas_asu_brand_test/drupal/modules/mmenavas_asu_brand
  - cd travis_ci_drupal_module_example_test/drupal
  - drush --yes pm-enable mmenavas_asu_brand

#script: drush test-run 'Travis-CI Drupal Module Example' --uri=http://127.0.0.1:8080
script: echo "Hello world"
