language: php

php:
  - 7.0

matrix:
  fast_finish: true

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  - composer global require drush/drush:drush-8.1.13

  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

before_script:
  - pwd
  - ls -al
  - cd ..
  - pwd
  - ls -al
  - mysql -e 'create database drupal'
  - drush --version
  - drush --yes core-quick-drupal mmenavas --no-server --db-url=mysql://root:@127.0.0.1/drupal --profile=minimal
  - ls -al

#script: drush test-run 'Travis-CI Drupal Module Example' --uri=http://127.0.0.1:8080
script: drush en asu_brand -y
